### ISSUE TITLE
[Props] Karaoke mic stand rotates when it isn't supposed to.

### ISSUE THREAD

**Issue by Shockwave508** [NightFright2k19/duke3d_voxelpack#75]
In certain levels in both DN3D and Duke It Out In D.C., the mic stand prop slowly spins in place, or it may spin faster depending on how fast you move towards it.
![Screenshot_2021-07-07-09-27-17-429_com opentouchgaming razetouch](https://user-images.githubusercontent.com/32436386/124781672-357cc080-df09-11eb-85a1-891dcdfe7b15.jpg)

**Comment by NightFright2k19** [comment]
Which EDuke32 snapshot are you using exactly? I cannot reproduce this issue with a recent snapshot on my end.

**Comment by NightFright2k19** [comment]
Raze issue, so...

**Comment by ChapyGuy** [comment]
This is an old issue, but I'm still having this happen in Raze. The microphone in the conference room on Hell to the Chief in Duke DC spins like crazy, but it's fine in EDuke32. I've commented out the microphone for now and made a post on the ZDoom forums since I couldn't find anything there about this issue.
